### ISSUE TITLE
How can I use DDP

### ISSUE THREAD

**Issue by ldt17** [titanmu/RoadCrackDetection#6]
I successfully completed training on one GPU but when I tried to use python - m torch. distributed. launch -- nproc_ per_ Node 2 failed. This trouble bothered me for a few days .I hardly changed the code except for part of the loss function.There are no changes in train_main.py.

# Initialize distributed training
    if device.type != 'cpu' and torch.cuda.device_count() > 1 and torch.distributed.is_available():
        '''
        dist.init_process_group(backend='nccl',  # distributed backend
                                init_method='tcp://127.0.0.1:9999',  # init method 
                                world_size=1,  # number of nodes
                                rank=0)  # node rank
        '''
        print("start try distributed training")
        print("local_rank :",opt.local_rank)
        dist.init_process_group(backend='gloo',  # distributed backend
                                init_method="env://")
                                #init_method=opt.init_method,  # init method 
                                #world_size=opt.word_size,  # number of nodes
                                #rank=opt.rank)  # node rank
                                   
        print("Distributed training initialization completed")
        model = torch.nn.parallel.DistributedDataParallel(model)#,find_unused_parameters=True)
        #find_unused_parameters=True
        print("Distributed training is set up")

 I use gloo because nccl is not installed on the host.I only use one host and there are up to four GPUs on this host.After several days of trying, it is found that some parameters of forward do not belong to NN. Module class, resulting in some parameters not being copied to other GPUs.

Here is the error message.

Traceback (most recent call last):
  File "train_main.py", line 448, in <module>
    train(hyp)
  File "train_main.py", line 292, in train
    pred = model(imgs)
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 708, in forward
    outputs = self.parallel_apply(self._module_copies[:len(inputs)], inputs, kwargs)
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 784, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/px003/RoadCrackDetection-master/Proposed Algorithm/models/yolo.py", line 91, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/px003/RoadCrackDetection-master/Proposed Algorithm/models/yolo.py", line 108, in forward_once
    x = m(x)  # run
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/px003/RoadCrackDetection-master/Proposed Algorithm/models/common.py", line 54, in forward
    y1 = self.cv3(self.m(self.cv1(x)))
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/px003/RoadCrackDetection-master/Proposed Algorithm/models/common.py", line 37, in forward
    return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 9.78 GiB total capacity; 1.67 GiB already allocated; 4.06 MiB free; 5.16 GiB reserved in total by PyTorch)

Killing subprocess 29746
Killing subprocess 29747
Traceback (most recent call last):
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/px003/.conda/envs/yolov5/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/px003/.conda/envs/yolov5/bin/python', '-u', 'train_main.py', '--local_rank=1', '--data', 'data/pave.yaml', '--cfg', 'models/yolov5l_pave.yaml', '--batch-size', '2']' returned non-zero exit status 1.

**Comment by ldt17** [comment]
I tried to solve this problem. After continuous print debugging, it was found that the model parameters were not copied to the GPU. In detail, the list appears after the input x passes the model (x), and the list does not belong to the subclass of Module or Tensor, so it cannot be copied to GPU
